# docker compose -f .\docker-compose-local.yml up -d (detached mode)
version: '3.7'
networks:
  e_learning_support:
    name: elearning_support_network
    external: true
services:
  fe_app:
    container_name: elearning_support_fe
    image: leopepe2012/elearning_support_system:fe-mpec
    restart: always
    privileged: true
    user: root
    environment:
      - "NODE_ENV=mpec"
      - "TZ=Asia/Ho_Chi_Minh"
    networks:
      - e_learning_support
    volumes:
      - /usr/local:/usr/local
    ports:
      - "80:80"
    expose:
      - 80